TOP=../../..

include $(TOP)/makefiles/docdefs.mk


JAVAC=$(JAVAC1.6)

DESTFILES=Lookup.class List.class ListBindings.class \
	Bind.class Rebind.class Unbind.class \
	Rename.class Create.class Destroy.class \
	Search.class SearchCountLimit.class SearchTimeLimit.class \
	SearchObject.class SearchRetAll.class SearchWithFilter.class \
	SearchWithFilterObjs.class SearchWithFilterRetAll.class

include $(MAKEFILE_PATH)/examplerules.mk
